version: 0.2

phases:
  pre_build:
    commands:
      - echo [INFO] Change timezone
      - export TZ="Asia/Tokyo"
      - pwd
      - ls -l /app/
      - ls -l /app/cache/
      - ls -l /app/cache/com/
      - ls -l /root/.m2/
      - ls -l /root/.m2/repository/
      - ls -l /root/.m2/repository/com/
  build:
    commands:
      - echo [INFO] Test started on `date`
      - mvn test

cache:
  paths:
    - '/root/.m2/**/*'
